name: Feature Request
description: Suggest a new feature for pyhelper-jkluess
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! This will result in a **minor version bump** (0.X.0) when implemented.
        
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: What feature would you like to see?
      placeholder: I would like to have...
    validations:
      required: true
      
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: What problem does this solve? How would you use it?
      placeholder: This would help with...
    validations:
      required: true
      
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the library does this relate to?
      options:
        - Trees
        - Graphs
        - Lists (Linked, Double, Circular)
        - Skip Lists
        - General/Other
    validations:
      required: true
      
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information, examples, or references?
